[tool.poetry]
name = "textual"
version = "0.1.15"
homepage = "https://github.com/Textualize/textual"
description = "Text User Interface using Rich"
authors = ["Will McGugan <willmcgugan@gmail.com>"]
license = "MIT"
classifiers = [
    "Development Status :: 1 - Planning",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Operating System :: MacOS",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
]

[tool.poetry.scripts]
textual = "textual.cli.cli:run"

[tool.poetry.dependencies]
python = "^3.7"
rich = "^12.3.0"

#rich = {git = "git@github.com:willmcgugan/rich", rev = "link-id"}
click = "8.1.2"
importlib-metadata = "^4.11.3"
typing-extensions = { version = "^4.0.0", python = "<3.8" }
msgpack = "^1.0.3"
mkdocs-material = "^8.2.14"
mkdocstrings = "^0.18.1"
mkdocs-plugin-inline-svg = "^0.1.0"

[tool.poetry.dev-dependencies]
Jinja2 = "3.0.3"
pytest = "^6.2.3"
black = "^22.3.0"
mypy = "^0.950"
pytest-cov = "^2.12.1"
pre-commit = "^2.13.0"
pytest-aiohttp = "^1.0.4"
time-machine = "^2.6.0"

[tool.black]
includes = "src"

[tool.pytest.ini_options]
asyncio_mode = "auto"
testpaths = ["tests"]
markers = [
    "integration_test: marks tests as slow integration tests(deselect with '-m \"not integration_test\"')",
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
